HREmployeeManagementApp/EmployeeHandler/Controllers/AdminDashboardController.cs
using Management.Application.Interfaces;
using Management.Entities.AdminEntities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace EmployeeHandler.Controllers;
public class AdminDashboardController : Controller
{
    private readonly IEmployeeRepository _employeeRepository;
    private readonly IAttendanceRepository _attendanceRepository;

    public AdminDashboardController(IEmployeeRepository employeeRepository,IAttendanceRepository attendanceRepository)
    {
        _employeeRepository = employeeRepository;
        _attendanceRepository = attendanceRepository;
    }

    public async Task<IActionResult> AdminDashboard(int EmployeeID, int AdminID)
    {
#nullable disable
        var adminSession = JsonConvert.DeserializeObject<AdminPersonal>(HttpContext.Session.GetString("AdminSession"));
        EmployeeID = adminSession.EmployeeID;
        AdminID = adminSession.AdminID;
#nullable enable
        var response = await _employeeRepository.GetAdminByIdAsync(EmployeeID,AdminID);
        return View(response);
    }

    public async Task<IActionResult> PendingLeaveRequestsPartial()
    {
        var response = await _attendanceRepository.PendingLeaveRequestAsync();
        return PartialView("_PendingLeaveRequests",response);
    }

    public async Task<IActionResult> PendingRegularizationRequestsPartial()
    {
        var response = await _attendanceRepository.PendingRegularizationRequestAsync();
        return PartialView("_PendingRegularizationRequests", response);
    }
}

HREmployeeManagementApp/EmployeeHandler/Controllers/AttendanceAdminController.cs
using Management.Application.Interfaces;
using Management.Entities.AdminEntities;
using Management.Entities.AttendanceEntities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;

namespace EmployeeHandler.Controllers;
public class AttendanceAdminController : Controller
{
    private readonly IAttendanceRepository _attendanceRepository;

    public AttendanceAdminController(IAttendanceRepository attendanceRepository)
    {
        _attendanceRepository = attendanceRepository;
    }

    [HttpGet]
    public async Task<IActionResult> EmployeeAttendanceList(int employeeID, DateTime date)
    {
        date = DateTime.Today;
        var result = await _attendanceRepository.GetAttendanceAdminByIDAndDateAsync(employeeID, date);
        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> LeaveRecord()
    {
        var response = await _attendanceRepository.GetAllLeavesAsync();
        return View(response);
    }


    [HttpGet]
    public async Task<IActionResult> RegularizationRecord()
    {
        var response = await _attendanceRepository.GetAllRegularizationsAsync();
        return View(response);
    }


    [HttpGet]
    public async Task<IActionResult> CheckLeaveRequest(int leaveID)
    {
        var response = await _attendanceRepository.GetLeaveByID(leaveID);
        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> ConfirmLeaveRequest(LeaveAdmin leaveAdmin)
    {
        if (leaveAdmin.ApprovalStatus != true)
        {
            leaveAdmin.ApprovalStatus = false;
        }
#nullable disable
        var adminSession = JsonConvert.DeserializeObject<AdminPersonal>(HttpContext.Session.GetString("AdminSession"));
        leaveAdmin.AdministeredBy = $"{adminSession.FirstName} {adminSession.LastName}";
#nullable enable
        var response = await _attendanceRepository.UpdateLeaveRequest(leaveAdmin);


        return RedirectToAction("AdminDashboard", "AdminDashboard", new {AdminID = adminSession.AdminID, EmployeeID = adminSession.EmployeeID});
    }

    [HttpGet]
    public async Task<IActionResult> CheckRegularizationRequest(int regularizeID)
    {
        var response = await _attendanceRepository.GetRegualrizationByID(regularizeID);
        return View(response);
    }
    
    [HttpPost]
    public async Task<IActionResult> ConfirmRegularizationRequest(RegularizationAdmin regularizationAdmin)
    {
        if (regularizationAdmin.Approved != true)
        {
            regularizationAdmin.Approved = false;
        }
#nullable disable
        var adminSession = JsonConvert.DeserializeObject<AdminPersonal>(HttpContext.Session.GetString("AdminSession"));
        regularizationAdmin.RegularizedBy = $"{adminSession.FirstName} {adminSession.LastName}";
#nullable enable
        var response = await _attendanceRepository.UpdateRegularizationRequest(regularizationAdmin);


        return RedirectToAction("AdminDashboard", "AdminDashboard", new {AdminID = adminSession.AdminID, EmployeeID = adminSession.EmployeeID});
    }


}

HREmployeeManagementApp/EmployeeHandler/Controllers/EmployeeAdminController.cs
using Management.Application.Interfaces;
using Management.Entities.AdminEntities;
using Management.Entities.EmployeeEntities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace EmployeeHandler.Controllers;
public class EmployeeAdminController : Controller
{
    private readonly IEmployeeRepository _employeeRepository;

    public EmployeeAdminController(IEmployeeRepository employeeRepository)
    {
        _employeeRepository = employeeRepository;
    }

    [HttpGet]
    public async Task<IActionResult> EmployeeList()
    {
        var result = await _employeeRepository.GetAllEmployeesAsync();
        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> EmployeeDetailsUpdate(int EmployeeID)
    {
        var employeeData = await _employeeRepository.GetEmployeeByIdAsync(EmployeeID);
        return View(employeeData);
    }

    [HttpPost]
    public async Task<IActionResult> EmployeeDetailsUpdate(EmployeeAdmin employee)
    {
#nullable disable
        var adminSession = JsonConvert.DeserializeObject<AdminPersonal>(HttpContext.Session.GetString("AdminSession"));
        employee.ModifiedBy = $"{adminSession.FirstName} {adminSession.LastName}";
#nullable enable
        employee.ModifiedDate = DateTime.Today;

        var result = await _employeeRepository.UpdateEmployeeByIdAsync(employee);
        return RedirectToAction("EmployeeList");
    }
}

HREmployeeManagementApp/EmployeeHandler/Views/AdminDashboard/AdminDashboard.cshtml
@model AdminPersonal

@section head{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
}

<style>
    .dashboard{
        max-width:100% !important;
        height:100% !important;
    }
    
    .sidebar {
        height: 100%;
		background-color: #007bff;
        padding: 20px;
        color:white;
    }

    .sidebarItem > a{
        color: white;
        text-decoration:none;
    }

    .sidebarItem{
        margin-top: 2rem;
        margin-left: 1rem;

    }

    .main-area {
        padding: 20px;
    }

    .card-header {
        background-color: #007bff;
        color: #fff;
        padding: 10px;
    }

    .cardsize{
        width:70%; 
        text-align:center
    }
</style>

<section>
    <div class="container dashboard">
        <div class="row">
        
            <div class="col-lg-2 sidebar">
                <div class="sidebarItem"><h6>Admin: </h6></div>
                <div style="padding:.25rem .25rem; color: #007bff; background-color:white; text-align:center;"><h5 style="">@Model.FirstName @Model.LastName</h5></div>
                <div class="list-group">
					<div class="sidebarItem"><a href="@Url.Action("EmployeeList","EmployeeAdmin")"><h6>Employee Details</h6></a></div>
					<div class="sidebarItem"><a href="@Url.Action("RegularizationRecord","AttendanceAdmin")"><h6>Regulariztion Record</h6></a></div>
                    <div class="sidebarItem"><a href="@Url.Action("LeaveRecord","AttendanceAdmin")"><h6>Leave Record</h6></a></div>
                </div>
            </div>


		    <div class="col-md-10 main">
			    <h1 align="center">All Requests</h1>
                <div class="row mt-5">
                    
                    <!-- Regularization Requests -->
                    <div class="col-lg-6">
                        <div class="mx-auto cardsize">
                        <div class="card">
                            <div class="card-header">
                                <h5 class="mb-0">Regularization Requests</h5>
                            </div>
                                <div id="pendingRegularizationRequests">

                                </div>
						    </div>
						</div>
                    </div>

                    <!-- Leave Requests -->
                    <div class="col-lg-6">
                        <div class="mx-auto cardsize">
                            <div class="card">
                                <div class="card-header">
                                    <h5 class="mb-0">Leave Requests</h5>
                                </div>
                                <div id="pendingLeaveRequests">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
	    </div>
    </div>
@section Scripts{
    <script>
            $('#pendingLeaveRequests').load("/AdminDashboard/PendingLeaveRequestsPartial")
    </script>
    <script>
            $('#pendingRegularizationRequests').load("/AdminDashboard/PendingRegularizationRequestsPartial")
    </script>
}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</section>

HREmployeeManagementApp/EmployeeHandler/Views/AdminDashboard/_PendingLeaveRequests.cshtml
@model List<LeaveAdmin>

<div>
<div class="list-group list-group-flush">
    @foreach (LeaveAdmin request in Model)
    {
        <a href="@Url.Action("CheckLeaveRequest","AttendanceAdmin",new {LeaveID = request.LeaveID})">
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <span>@request.ToDate.ToString("dd/MMM/yyyy")</span>
                <span>@request.Reason</span>
            </div>
        </a>
    }
</div>
</div>

HREmployeeManagementApp/EmployeeHandler/Views/AdminDashboard/_PendingRegularizationRequests.cshtml
@model List<RegularizationAdmin>

<div>
    <div class="list-group list-group-flush">
        @foreach(RegularizationAdmin request in Model)
        {
            <a href="@Url.Action("CheckRegularizationRequest","AttendanceAdmin",new {RegularizeID = request.RegularizeID})">
            <div class="list-group-item d-flex justify-content-between align-items-center">
                <span>@request.RegularizeDate.ToString("dd/MM/yyyy")</span>
                <span>@request.Reason</span>
            </div>
            </a>
        }
	</div>
</div>