HREmployeeManagementApp/EmployeeHandler/Controllers/AttendancePersonalController.cs
using Management.Application.Interfaces;
using Management.Entities.AttendanceEntities;
using Management.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeHandler.Controllers;
public class AttendancePersonalController : Controller
{
    private readonly IAttendanceRepository _attendanceRepository;

    public AttendancePersonalController(IAttendanceRepository attendanceRepository)
    {
        _attendanceRepository = attendanceRepository;
    }

    [HttpGet]
    public IActionResult Leave(int employeeID)
    {
        var response = new LeavePersonal();
        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> LeaveRequest(LeavePersonal leavePersonal)
    {
        leavePersonal.DateOfRequest = DateTime.Now;
        var leaveRequest = await _attendanceRepository.LeaveRequestAsync(leavePersonal);
        TempData["LeaveRequestID"] = leaveRequest.LeaveID;
        return RedirectToAction("Leave", new {EmployeeID = leaveRequest.EmployeeID, LeaveRequestID = leaveRequest.LeaveID});
    }

    [HttpGet]
    public IActionResult RegularizationForm()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> RegularizeRequest(EmployeeRegularization regularization)
    {
        var requestDetails = await _attendanceRepository.RegularizationRequestAsync(regularization);
        TempData["RegularizeRequest"] = requestDetails.RegularizeID;
        return RedirectToAction("GetPersonalDetails", "EmployeePersonal",
            new { EmployeeID  = requestDetails.EmployeeID, RegularizeID = requestDetails.RegularizeID});
    }


    [HttpGet]
    public async Task<IActionResult> AttendanceDetails(int employeeID)
    {
        //Getting the parameter from query string as string and converting it to employeeID which is Integer//        
        string? stringEmployeeID = HttpContext.Request.Query["EmployeeID"];
        int.TryParse(stringEmployeeID, out employeeID);
        /****************************************************************************************************/

        var result = await _attendanceRepository.GetAttendancePersonalAsync(employeeID);

        return View(result);
    }
}

HREmployeeManagementApp/EmployeeHandler/Views/AttendancePersonal/AttendanceDetails.cshtml
@model List<AttendancePersonal>

@section head{
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
}

@{
    var employeeID = Context.Request.Query["EmployeeID"];
}

<style>
    .regularizelink{
        visibility:hidden;
    }

    .regularize:hover > td > .regularizelink{
        visibility: visible;
    }
</style>

<section id="tabs" class="project-tab">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <nav>
                    <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" role="tab" aria-controls="nav-home" aria-selected="true">Attendance Details</a>
                        <a href="@Url.Action("Leave", "AttendancePersonal", new {EmployeeID = employeeID})" class="nav-item nav-link" >Apply Leave</a>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <table class="table" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Check In</th>
                                    <th>Check Out</th>
                                    <th>Status</th>
                                    <th>Regularized</th>

                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var attendance in Model)
                                {
                                    <tr class="regularize">
                                        <td>@attendance.Date.ToString("dd/MMM/yyyy")</td>
                                        <td>@attendance.CheckIn</td>
                                        <td>@attendance.CheckOut</td>
                                        <td>@attendance.Status</td>                                        
                                    @if (attendance.ModifiedBy != null)
                                        {<td style="padding-left:3.3vw;"><img width="20" height="20" src="/confirm-icon_black.svg" /></td>}
                                        else{
                                        <td>
                                            <span class="regularizelink">
                                                @Html.ActionLink("Regularize","RegularizationForm","AttendancePersonal",
                                            new{ EmployeeID = employeeID, AttendanceID = attendance.AttendanceID, AttendanceDate = attendance.Date.ToString("yyyy-MM-dd"),
                                                    CheckIn = attendance.CheckIn, CheckOut = attendance.CheckOut},null)
                                            </span>
                                        </td>}
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>

HREmployeeManagementApp/EmployeeHandler/Views/AttendancePersonal/Leave.cshtml
@model LeavePersonal

@section head{
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
}

@{
    var employeeID = Context.Request.Query["EmployeeID"];
    var successfulRequest = TempData["LeaveRequestID"];
}

<style>
    body{
        background-image: linear-gradient(#0062cc,white,white);
        background-size:cover;

    }
    nav {
        border-bottom: #eaedef 2px solid;
        background-color: white;
    }

    bgcolor{
        background-color: white;
    }

    form{
		border: 2px #0062cc solid;
        border-radius: 20px;
        background-image: linear-gradient(rgba(white, .1),rgba(white, .1));
    }
</style>

<section id="tabs" class="project-tab">
    <div class="container">
        <div class="row">
            <div class="col-md-12 bgcolor">
                <nav>
                    <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                        <a href="@Url.Action("AttendanceDetails", "AttendancePersonal", new{ EmployeeID = employeeID})" class="nav-item nav-link" >Attendance Details</a>
                        <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" role="tab" aria-controls="nav-profile" aria-selected="false">Apply Leave</a>
                    </div>
                </nav>
                <div class="tab-content mt-5" id="nav-tabContent">
                    <div class="tab-pane fade show active row" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        
                            <form class="bg-light py-4 px-4 mx-auto col-6 " asp-action="LeaveRequest" method="post">
                            <h1>Leave Application Form</h1>
                            <div class="NeededExtras">
                                <input type="hidden" value="@employeeID" asp-for="EmployeeID">
                            </div>
							<div class="row mt-3">
                                <div class="row my-3 col" id="SetLeave">
                                    <div class="col">
                                        <label>Date From *</label>
                                        <input id="setLeaveFrom" type="date" value="2023-01-01" id="datePickerId" class="form-control input-sm" required asp-for="DateFrom">
                                    </div>
                                    <div class="col">
                                        <label>To Date *</label>
                                        <input id="setLeaveTo" type="date" value="2023-01-01" class="form-control input-sm" required asp-for="ToDate">
                                    </div>
                                </div>
                            </div>
                            <div class="col mt-3">                                
                                <label for="reason">Reason *</label>
                                <textarea type="text" class="form-control input-sm col" id="reason" rows="3" required asp-for="Reason"></textarea>
                            </div>
                            <div class="row mx-auto my-3">
                                <input class="btn btn-outline-primary mx-auto col-6" type="submit">
                            </div>
                        </form>
                    </div>
                    
                </div>
            </div>

            @if (successfulRequest != null)
            {
                <div class="alert alert-warning">
                <span>Your Request : No.@successfulRequest was successful.</span>
                <script>alert(Your Request : No.@successfulRequest was succesful)</script>
        </div>
            }
        </div>
    </div>
</section>

                                    

HREmployeeManagementApp/EmployeeHandler/Views/AttendancePersonal/RegularizationForm.cshtml
@model EmployeeRegularization

@section head{
    <!-- Include Bootstrap CDN -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
}

@{
    var employeeID = Context.Request.Query["EmployeeID"];
    var attendanceID = Context.Request.Query["AttendanceID"];
    var attendanceDate = Context.Request.Query["AttendanceDate"];
    var checkIn = Context.Request.Query["CheckIn"];
    var checkOut = Context.Request.Query["CheckOut"];
}

<style>
    body {
        background-image: linear-gradient(#0062cc,white,white);
        background-size: cover;
    }

    nav {
        border-bottom: #eaedef 1px solid;
    }

    form {
        border: 2px #0062cc solid;
        border-radius: 20px;
        background-image: linear-gradient(rgba(white, .1),rgba(white, .1));
    }
</style>

<section id="tabs" class="project-tab">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <div class="mt-lg-5 p-lg-4 mx-auto col-10 col-md-8 col-lg-6">
                            <form class="bg-light py-4 px-4" asp-action="RegularizeRequest" method="post">
                                <h1>Regularization Form</h1>
                                <div class="row mt-3">
                                    <div class="col">
                                        <label for="AttendanceDate">Attendance Date</label>
                                        <input type="date" class="form-control input-sm" placeholder="" readonly value=@attendanceDate asp-for="RegularizeDate">
                                    </div>
                                    <div class="col">
                                        <label for="reason">Reason *</label>
                                        <select onchange="myFunction()" class="custom-select" id="reason" required asp-for="Reason">
                                            <option disabled selected hidden>PLease select a reason</option>
                                            <option value="Forgot To check In">Forgot To check In</option>
                                            <option value="Forgot To check Out">Forgot To check Out</option>
                                            <option value="Absent">Absent</option>
                                            <option value="Leave">Leave</option>
                                            <option value="Present">Present</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="row my-3 col">
                                        <div class="col">
                                            <label>Check In - Recorded</label>
                                            <input type="time" class="form-control input-sm" readonly value="@checkIn" asp-for="CheckedIn">
                                        </div>
                                        <div class="col mt-2">
                                            <label>Check Out - Recorded</label>
                                            <input type="time" class="form-control input-sm" readonly value="@checkOut" asp-for="CheckedOut">
                                        </div>
                                    </div>
                                    <div class="row my-3 col" id="SetChecks">
                                        <div class="col">
                                            <label>Set Check In *</label>
                                            <input id="setCheckIn" type="time" step="1" class="form-control input-sm" required asp-for="AppliedCheckIn">
                                        </div>
                                        <div class="col mt-2">
                                            <label>Set Check Out *</label>
                                            <input id="setCheckOut" type="time" step="1" class="form-control input-sm" required asp-for="AppliedCheckOut">
                                        </div>
                                    </div>
                                </div>
                                <div class="NeededExtras">
                                    <input type="hidden" value="@attendanceID" asp-for="AttendanceID">
                                    <input type="hidden" value="@employeeID" asp-for="EmployeeID">
                                </div>
                                <div class="row mx-auto my-3">
                                    <input class="btn btn-outline-primary col" type="submit">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('#reason').change(function () {
                var selectX = $('#reason').val();
                if (selectX === "Absent" || selectX === "Leave") {
                    $("#setCheckIn").attr('disabled', 'disabled');
                    $("#setCheckOut").attr('disabled', 'disabled');
                } else {
                    $("#setCheckIn").removeAttr('disabled');
                    $("#setCheckOut").removeAttr('disabled');
                }
            })
        });

    </script>
</section>
           