HREmployeeManagementApp/EmployeeHandler/Controllers/EmployeeAdminController.cs
using Management.Application.Interfaces;
using Management.Entities.AdminEntities;
using Management.Entities.EmployeeEntities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace EmployeeHandler.Controllers;
public class EmployeeAdminController : Controller
{
    private readonly IEmployeeRepository _employeeRepository;

    public EmployeeAdminController(IEmployeeRepository employeeRepository)
    {
        _employeeRepository = employeeRepository;
    }

    [HttpGet]
    public async Task<IActionResult> EmployeeList()
    {
        var result = await _employeeRepository.GetAllEmployeesAsync();
        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> EmployeeDetailsUpdate(int EmployeeID)
    {
        var employeeData = await _employeeRepository.GetEmployeeByIdAsync(EmployeeID);
        return View(employeeData);
    }

    [HttpPost]
    public async Task<IActionResult> EmployeeDetailsUpdate(EmployeeAdmin employee)
    {
#nullable disable
        var adminSession = JsonConvert.DeserializeObject<AdminPersonal>(HttpContext.Session.GetString("AdminSession"));
        employee.ModifiedBy = $"{adminSession.FirstName} {adminSession.LastName}";
#nullable enable
        employee.ModifiedDate = DateTime.Today;

        var result = await _employeeRepository.UpdateEmployeeByIdAsync(employee);
        return RedirectToAction("EmployeeList");
    }
}

HREmployeeManagementApp/EmployeeHandler/Controllers/LoginController.cs
using Management.Application.Interfaces;
using Management.Core.Models;
using Management.Entities.AdminEntities;
using Management.Entities.EmployeeEntities;
using Management.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace EmployeeHandler.Controllers;
public class LoginController : Controller
{
    private readonly IEmployeeRepository _employeeRepository;
    public LoginController(IEmployeeRepository employeeRepository)
    {
        _employeeRepository = employeeRepository;
    }

    public IActionResult Login()
    {
        var response = new LoginViewModel();
        return View(response);
    }


    [HttpPost]
    public async Task<IActionResult> Login(EmployeeLogin employeeLogin)
    {
        var response = await _employeeRepository.CheckEmployeeAysnc(employeeLogin);


        if (response == 0)
        {
            // Credentials are invalid, return an error message or redirect to a login failure page
            TempData["Error"] = ("Credentials are invalid. Please try again.");
            return View();

        }
        else
        {
            var employee = new EmployeePersonal() { EmployeeID = response};
            HttpContext.Session.SetString("EmployeeSession",JsonConvert.SerializeObject(employee));
            // Credentials are valid, perform the desired action
            var url = Url.Action("GetPersonalDetails", "EmployeePersonal", new { EmployeeID = response });
            /*Using assert to declare that "url" will never be null so Redirect doesnt show null warning*/
            Debug.Assert(url != null, "The generated URL should not be null.");
            return Redirect(url);
        }
    }

    public IActionResult AdminLogin()
    {
        return View();
    }


    [HttpPost]
    public async Task<IActionResult> AdminLogin(AdminLogin adminLogin)
    {
        var response = await _employeeRepository.CheckAdminAsync(adminLogin);

        if (response is null)
        {
            // Credentials are invalid, return an error message or redirect to a login failure page
            TempData["AdminError"] = ("You are not an Administrator.");
            return View();
        }
        else
        {
            var profile = await _employeeRepository.GetAdminByIdAsync(response.EmployeeID, response.AdminID);
            //var admin = new AdminPersonal() { AdminID = profile.AdminID, EmployeeID = profile.EmployeeID, FirstName = profile.FirstName, LastName = profile.LastName};
            HttpContext.Session.SetString("AdminSession", JsonConvert.SerializeObject(profile));
            // Credentials are valid, perform the desired action
            //var url = Url.Action("AdminDashboard", "AdminDashboard", new { AdminID = response.AdminID, EmployeeID = response.EmployeeID });
            /*Using assert to declare that "url" will never be null so Redirect doesnt show null warning*/
            //Debug.Assert(url != null, "The generated URL should not be null.");
            return RedirectToAction("AdminDashboard", "AdminDashboard", new { AdminID = response.AdminID, EmployeeID = response.EmployeeID });
        }
    }
}

HREmployeeManagementApp/EmployeeHandler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/@(nameof(EmployeeHandler)).styles.css" type="text/css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeHandler.styles.css" type="text/css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />

    @RenderSection("head",false)
        
    <style>
        /* Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
        for details on configuring this project to bundle and minify static web assets. */

        a.navbar-brand {
            white-space: normal;
            text-align: center;
            word-break: break-all;
        }

        a {
            color: #0077cc;
        }

        .btn-primary {
            color: #fff;
            background-color: #1b6ec2;
            border-color: #1861ac;
        }

        .nav-pills .nav-link.active, .nav-pills .show > .nav-link {
            color: #fff;
            background-color: #1b6ec2;
            border-color: #1861ac;
        }

        .border-top {
            border-top: 1px solid #e5e5e5;
        }

        .border-bottom {
            border-bottom: 1px solid #e5e5e5;
        }

        .box-shadow {
            box-shadow: 0 .25rem .75rem rgba(0, 0, 0, .05);
        }

        button.accept-policy {
            font-size: 1rem;
            line-height: inherit;

        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            white-space: nowrap;
            line-height: 60px;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeAdmin" asp-action="EmployeeList">Employee List for Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminDashboard" asp-action="AdminDashboard">Admin Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ApplicantRegistration">Applicant Registartion</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container dashboard">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @*<div class="container">
            &copy; 2023 - EmployeeHandler - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>